# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'address_data_check.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    #onClicked = pyqtSignal()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(393, 539)
        self.chkA0 = QtWidgets.QCheckBox(Dialog)
        self.chkA0.setGeometry(QtCore.QRect(20, 80, 70, 17))
        self.chkA0.setObjectName("chkA0")
        self.chkA1 = QtWidgets.QCheckBox(Dialog)
        self.chkA1.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.chkA1.setObjectName("chkA1")
        self.chkA3 = QtWidgets.QCheckBox(Dialog)
        self.chkA3.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.chkA3.setObjectName("chkA3")
        self.chkA2 = QtWidgets.QCheckBox(Dialog)
        self.chkA2.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.chkA2.setObjectName("chkA2")
        self.chkA5 = QtWidgets.QCheckBox(Dialog)
        self.chkA5.setGeometry(QtCore.QRect(20, 180, 70, 17))
        self.chkA5.setObjectName("chkA5")
        self.chkA6 = QtWidgets.QCheckBox(Dialog)
        self.chkA6.setGeometry(QtCore.QRect(20, 200, 70, 17))
        self.chkA6.setObjectName("chkA6")
        self.chkA4 = QtWidgets.QCheckBox(Dialog)
        self.chkA4.setGeometry(QtCore.QRect(20, 160, 70, 17))
        self.chkA4.setObjectName("chkA4")
        self.chkA7 = QtWidgets.QCheckBox(Dialog)
        self.chkA7.setGeometry(QtCore.QRect(20, 220, 70, 17))
        self.chkA7.setObjectName("chkA7")
        self.led1 = LedWidget(Dialog)
        self.led1.setGeometry(QtCore.QRect(80, 80, 21, 21))
        self.led1.setObjectName("led1")
        self.led2 = LedWidget(Dialog)
        self.led2.setGeometry(QtCore.QRect(80, 100, 21, 21))
        self.led2.setObjectName("led2")
        self.led3 = LedWidget(Dialog)
        self.led3.setGeometry(QtCore.QRect(80, 120, 21, 21))
        self.led3.setObjectName("led3")
        self.led4 = LedWidget(Dialog)
        self.led4.setGeometry(QtCore.QRect(80, 140, 21, 21))
        self.led4.setObjectName("led4")
        self.led6 = LedWidget(Dialog)
        self.led6.setGeometry(QtCore.QRect(80, 180, 21, 21))
        self.led6.setObjectName("led6")
        self.led5 = LedWidget(Dialog)
        self.led5.setGeometry(QtCore.QRect(80, 160, 21, 21))
        self.led5.setObjectName("led5")
        self.led8 = LedWidget(Dialog)
        self.led8.setGeometry(QtCore.QRect(80, 220, 21, 21))
        self.led8.setObjectName("led8")
        self.led7 = LedWidget(Dialog)
        self.led7.setGeometry(QtCore.QRect(80, 200, 21, 21))
        self.led7.setObjectName("led7")
        self.lblBank2 = QtWidgets.QLabel(Dialog)
        self.lblBank2.setGeometry(QtCore.QRect(170, 60, 71, 16))
        self.lblBank2.setObjectName("lblBank2")
        self.lblBank1 = QtWidgets.QLabel(Dialog)
        self.lblBank1.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.lblBank1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lblBank1.setObjectName("lblBank1")
        self.K19 = QtWidgets.QCheckBox(Dialog)
        self.K19.setGeometry(QtCore.QRect(170, 120, 70, 17))
        self.K19.setObjectName("K19")
        self.led19 = LedWidget(Dialog)
        self.led19.setGeometry(QtCore.QRect(230, 120, 21, 21))
        self.led19.setObjectName("led19")
        self.led21 = LedWidget(Dialog)
        self.led21.setGeometry(QtCore.QRect(230, 160, 21, 21))
        self.led21.setObjectName("led21")
        self.led17 = LedWidget(Dialog)
        self.led17.setGeometry(QtCore.QRect(230, 80, 21, 21))
        self.led17.setObjectName("led17")
        self.K18 = QtWidgets.QCheckBox(Dialog)
        self.K18.setGeometry(QtCore.QRect(170, 100, 70, 17))
        self.K18.setObjectName("K18")
        self.K21 = QtWidgets.QCheckBox(Dialog)
        self.K21.setGeometry(QtCore.QRect(170, 160, 70, 17))
        self.K21.setObjectName("K21")
        self.K22 = QtWidgets.QCheckBox(Dialog)
        self.K22.setGeometry(QtCore.QRect(170, 180, 70, 17))
        self.K22.setObjectName("K22")
        self.led22 = LedWidget(Dialog)
        self.led22.setGeometry(QtCore.QRect(230, 180, 21, 21))
        self.led22.setObjectName("led22")
        self.led24 = LedWidget(Dialog)
        self.led24.setGeometry(QtCore.QRect(230, 220, 21, 21))
        self.led24.setObjectName("led24")
        self.K20 = QtWidgets.QCheckBox(Dialog)
        self.K20.setGeometry(QtCore.QRect(170, 140, 70, 17))
        self.K20.setObjectName("K20")
        self.K24 = QtWidgets.QCheckBox(Dialog)
        self.K24.setGeometry(QtCore.QRect(170, 220, 70, 17))
        self.K24.setObjectName("K24")
        self.K17 = QtWidgets.QCheckBox(Dialog)
        self.K17.setGeometry(QtCore.QRect(170, 80, 70, 17))
        self.K17.setObjectName("K17")
        self.led20 = LedWidget(Dialog)
        self.led20.setGeometry(QtCore.QRect(230, 140, 21, 21))
        self.led20.setObjectName("led20")
        self.K23 = QtWidgets.QCheckBox(Dialog)
        self.K23.setGeometry(QtCore.QRect(170, 200, 70, 17))
        self.K23.setObjectName("K23")
        self.led18 = LedWidget(Dialog)
        self.led18.setGeometry(QtCore.QRect(230, 100, 21, 21))
        self.led18.setObjectName("led18")
        self.led23 = LedWidget(Dialog)
        self.led23.setGeometry(QtCore.QRect(230, 200, 21, 21))
        self.led23.setObjectName("led23")
        self.chkSelectbank1 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank1.setGeometry(QtCore.QRect(20, 420, 131, 17))
        self.chkSelectbank1.setObjectName("chkSelectbank1")
        self.led11 = LedWidget(Dialog)
        self.led11.setGeometry(QtCore.QRect(80, 280, 21, 21))
        self.led11.setObjectName("led11")
        self.chkA8 = QtWidgets.QCheckBox(Dialog)
        self.chkA8.setGeometry(QtCore.QRect(20, 240, 70, 17))
        self.chkA8.setObjectName("chkA8")
        self.led10 = LedWidget(Dialog)
        self.led10.setGeometry(QtCore.QRect(80, 260, 21, 21))
        self.led10.setObjectName("led10")
        self.chkA10 = QtWidgets.QCheckBox(Dialog)
        self.chkA10.setGeometry(QtCore.QRect(20, 280, 70, 17))
        self.chkA10.setObjectName("chkA10")
        self.led14 = LedWidget(Dialog)
        self.led14.setGeometry(QtCore.QRect(80, 340, 21, 21))
        self.led14.setObjectName("led14")
        self.chkA14 = QtWidgets.QCheckBox(Dialog)
        self.chkA14.setGeometry(QtCore.QRect(20, 360, 70, 17))
        self.chkA14.setObjectName("chkA14")
        self.led12 = LedWidget(Dialog)
        self.led12.setGeometry(QtCore.QRect(80, 300, 21, 21))
        self.led12.setObjectName("led12")
        self.led16 = LedWidget(Dialog)
        self.led16.setGeometry(QtCore.QRect(80, 380, 21, 21))
        self.led16.setObjectName("led16")
        self.led13 = LedWidget(Dialog)
        self.led13.setGeometry(QtCore.QRect(80, 320, 21, 21))
        self.led13.setObjectName("led13")
        self.led15 = LedWidget(Dialog)
        self.led15.setGeometry(QtCore.QRect(80, 360, 21, 21))
        self.led15.setObjectName("led15")
        self.chkA11 = QtWidgets.QCheckBox(Dialog)
        self.chkA11.setGeometry(QtCore.QRect(20, 300, 70, 17))
        self.chkA11.setObjectName("chkA11")
        self.chkA13 = QtWidgets.QCheckBox(Dialog)
        self.chkA13.setGeometry(QtCore.QRect(20, 340, 70, 17))
        self.chkA13.setObjectName("chkA13")
        self.chkA15 = QtWidgets.QCheckBox(Dialog)
        self.chkA15.setGeometry(QtCore.QRect(20, 380, 70, 17))
        self.chkA15.setObjectName("chkA15")
        self.chkA9 = QtWidgets.QCheckBox(Dialog)
        self.chkA9.setGeometry(QtCore.QRect(20, 260, 70, 17))
        self.chkA9.setObjectName("chkA9")
        self.chkA12 = QtWidgets.QCheckBox(Dialog)
        self.chkA12.setGeometry(QtCore.QRect(20, 320, 70, 17))
        self.chkA12.setObjectName("chkA12")
        self.led9 = LedWidget(Dialog)
        self.led9.setGeometry(QtCore.QRect(80, 240, 21, 21))
        self.led9.setObjectName("led9")
        self.led26 = LedWidget(Dialog)
        self.led26.setGeometry(QtCore.QRect(230, 260, 21, 21))
        self.led26.setObjectName("led26")
        self.K27 = QtWidgets.QCheckBox(Dialog)
        self.K27.setGeometry(QtCore.QRect(170, 280, 70, 17))
        self.K27.setObjectName("K27")
        self.K31 = QtWidgets.QCheckBox(Dialog)
        self.K31.setGeometry(QtCore.QRect(170, 360, 70, 17))
        self.K31.setObjectName("K31")
        self.K28 = QtWidgets.QCheckBox(Dialog)
        self.K28.setGeometry(QtCore.QRect(170, 300, 70, 17))
        self.K28.setObjectName("K28")
        self.K30 = QtWidgets.QCheckBox(Dialog)
        self.K30.setGeometry(QtCore.QRect(170, 340, 70, 17))
        self.K30.setObjectName("K30")
        self.led31 = LedWidget(Dialog)
        self.led31.setGeometry(QtCore.QRect(230, 360, 21, 21))
        self.led31.setObjectName("led31")
        self.K26 = QtWidgets.QCheckBox(Dialog)
        self.K26.setGeometry(QtCore.QRect(170, 260, 70, 17))
        self.K26.setObjectName("K26")
        self.led28 = LedWidget(Dialog)
        self.led28.setGeometry(QtCore.QRect(230, 300, 21, 21))
        self.led28.setObjectName("led28")
        self.led27 = LedWidget(Dialog)
        self.led27.setGeometry(QtCore.QRect(230, 280, 21, 21))
        self.led27.setObjectName("led27")
        self.chkSelectbank2 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank2.setGeometry(QtCore.QRect(170, 420, 121, 17))
        self.chkSelectbank2.setObjectName("chkSelectbank2")
        self.led29 = LedWidget(Dialog)
        self.led29.setGeometry(QtCore.QRect(230, 320, 21, 21))
        self.led29.setObjectName("led29")
        self.K25 = QtWidgets.QCheckBox(Dialog)
        self.K25.setGeometry(QtCore.QRect(170, 240, 70, 17))
        self.K25.setObjectName("K25")
        self.led30 = LedWidget(Dialog)
        self.led30.setGeometry(QtCore.QRect(230, 340, 21, 21))
        self.led30.setObjectName("led30")
        self.led32 = LedWidget(Dialog)
        self.led32.setGeometry(QtCore.QRect(230, 380, 21, 21))
        self.led32.setObjectName("led32")
        self.K32 = QtWidgets.QCheckBox(Dialog)
        self.K32.setGeometry(QtCore.QRect(170, 380, 70, 17))
        self.K32.setObjectName("K32")
        self.K29 = QtWidgets.QCheckBox(Dialog)
        self.K29.setGeometry(QtCore.QRect(170, 320, 70, 17))
        self.K29.setObjectName("K29")
        self.led25 = LedWidget(Dialog)
        self.led25.setGeometry(QtCore.QRect(230, 240, 21, 21))
        self.led25.setObjectName("led25")
        self.lblheader = QtWidgets.QLabel(Dialog)
        self.lblheader.setGeometry(QtCore.QRect(20, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblheader.setFont(font)
        self.lblheader.setObjectName("lblheader")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 460, 351, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lblboardid_2 = QtWidgets.QLabel(Dialog)
        self.lblboardid_2.setGeometry(QtCore.QRect(20, 440, 47, 13))
        self.lblboardid_2.setObjectName("lblboardid_2")
        self.chkA8.raise_()
        self.chkA0.raise_()
        self.chkA1.raise_()
        self.chkA3.raise_()
        self.chkA2.raise_()
        self.chkA5.raise_()
        self.chkA6.raise_()
        self.chkA4.raise_()
        self.chkA7.raise_()
        self.led1.raise_()
        self.led2.raise_()
        self.led3.raise_()
        self.led4.raise_()
        self.led6.raise_()
        self.led5.raise_()
        self.led8.raise_()
        self.led7.raise_()
        self.lblBank2.raise_()
        self.lblBank1.raise_()
        self.K19.raise_()
        self.led19.raise_()
        self.led21.raise_()
        self.led17.raise_()
        self.K18.raise_()
        self.K21.raise_()
        self.K22.raise_()
        self.led22.raise_()
        self.led24.raise_()
        self.K20.raise_()
        self.K24.raise_()
        self.K17.raise_()
        self.led20.raise_()
        self.K23.raise_()
        self.led18.raise_()
        self.led23.raise_()
        self.chkSelectbank1.raise_()
        self.led11.raise_()
        self.led10.raise_()
        self.chkA10.raise_()
        self.led14.raise_()
        self.chkA14.raise_()
        self.led12.raise_()
        self.led16.raise_()
        self.led13.raise_()
        self.led15.raise_()
        self.chkA11.raise_()
        self.chkA13.raise_()
        self.chkA15.raise_()
        self.chkA9.raise_()
        self.chkA12.raise_()
        self.led9.raise_()
        self.led26.raise_()
        self.K27.raise_()
        self.K31.raise_()
        self.K28.raise_()
        self.K30.raise_()
        self.led31.raise_()
        self.K26.raise_()
        self.led28.raise_()
        self.led27.raise_()
        self.chkSelectbank2.raise_()
        self.led29.raise_()
        self.K25.raise_()
        self.led30.raise_()
        self.led32.raise_()
        self.K32.raise_()
        self.K29.raise_()
        self.led25.raise_()
        self.lblheader.raise_()
        self.plainTextEdit.raise_()
        self.lblboardid_2.raise_()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.chkA0.setText(_translate("Dialog", "A0"))
        self.chkA1.setText(_translate("Dialog", "A1"))
        self.chkA3.setText(_translate("Dialog", "A3"))
        self.chkA2.setText(_translate("Dialog", "A2"))
        self.chkA5.setText(_translate("Dialog", "A5"))
        self.chkA6.setText(_translate("Dialog", "A6"))
        self.chkA4.setText(_translate("Dialog", "A4"))
        self.chkA7.setText(_translate("Dialog", "A7"))
        self.lblBank2.setText(_translate("Dialog", "DATA BITS"))
        self.lblBank1.setText(_translate("Dialog", "ADDRESS BITS"))
        self.K19.setText(_translate("Dialog", "K19"))
        self.K18.setText(_translate("Dialog", "K18"))
        self.K21.setText(_translate("Dialog", "K21"))
        self.K22.setText(_translate("Dialog", "K22"))
        self.K20.setText(_translate("Dialog", "K20"))
        self.K24.setText(_translate("Dialog", "K24"))
        self.K17.setText(_translate("Dialog", "K17"))
        self.K23.setText(_translate("Dialog", "K23"))
        self.chkSelectbank1.setText(_translate("Dialog", "Select All Address Bits"))
        self.chkA8.setText(_translate("Dialog", "A8"))
        self.chkA10.setText(_translate("Dialog", "A10"))
        self.chkA14.setText(_translate("Dialog", "A14"))
        self.chkA11.setText(_translate("Dialog", "A11"))
        self.chkA13.setText(_translate("Dialog", "A13"))
        self.chkA15.setText(_translate("Dialog", "A15"))
        self.chkA9.setText(_translate("Dialog", "A9"))
        self.chkA12.setText(_translate("Dialog", "A12"))
        self.K27.setText(_translate("Dialog", "K27"))
        self.K31.setText(_translate("Dialog", "K31"))
        self.K28.setText(_translate("Dialog", "K28"))
        self.K30.setText(_translate("Dialog", "K30"))
        self.K26.setText(_translate("Dialog", "K26"))
        self.chkSelectbank2.setText(_translate("Dialog", "Select all Data Bits"))
        self.K25.setText(_translate("Dialog", "K25"))
        self.K32.setText(_translate("Dialog", "K32"))
        self.K29.setText(_translate("Dialog", "K29"))
        self.lblheader.setText(_translate("Dialog", "ADDRESS AND DATA BITS CHECK"))
        self.lblboardid_2.setText(_translate("Dialog", "Console"))

from ledwidget import LedWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

