# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpio_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ledcontrol

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(550, 588)
        self.txtIP = QtWidgets.QPlainTextEdit(Dialog)
        self.txtIP.setGeometry(QtCore.QRect(70, 30, 121, 21))
        self.txtIP.setAcceptDrops(True)
        self.txtIP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtIP.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtIP.setObjectName("txtIP")
        self.K1 = QtWidgets.QCheckBox(Dialog)
        self.K1.setGeometry(QtCore.QRect(30, 120, 70, 17))
        self.K1.setObjectName("K1")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 140, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 180, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.GPIO1_2 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_2.setGeometry(QtCore.QRect(30, 160, 70, 17))
        self.GPIO1_2.setObjectName("GPIO1_2")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 220, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.GPIO1_3 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_3.setGeometry(QtCore.QRect(30, 240, 70, 17))
        self.GPIO1_3.setObjectName("GPIO1_3")
        self.GPIO1_4 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_4.setGeometry(QtCore.QRect(30, 200, 70, 17))
        self.GPIO1_4.setObjectName("GPIO1_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 260, 70, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 47, 13))
        self.label.setObjectName("label")
        self.txtSend = QtWidgets.QPlainTextEdit(Dialog)
        self.txtSend.setGeometry(QtCore.QRect(80, 520, 301, 21))
        self.txtSend.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSend.setObjectName("txtSend")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 520, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 550, 47, 13))
        self.label_3.setObjectName("label_3")
        self.txtRead = QtWidgets.QPlainTextEdit(Dialog)
        self.txtRead.setGeometry(QtCore.QRect(80, 550, 301, 21))
        self.txtRead.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtRead.setObjectName("txtRead")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 490, 47, 13))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(80, 490, 301, 21))
        self.plainTextEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.btnConnect = QtWidgets.QPushButton(Dialog)
        self.btnConnect.setGeometry(QtCore.QRect(200, 30, 51, 23))
        self.btnConnect.setObjectName("btnConnect")
        self.txtPORT = QtWidgets.QPlainTextEdit(Dialog)
        self.txtPORT.setGeometry(QtCore.QRect(70, 60, 121, 21))
        self.txtPORT.setAcceptDrops(True)
        self.txtPORT.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPORT.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPORT.setObjectName("txtPORT")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.label_5.setObjectName("label_5")
        self.btnSend = QtWidgets.QPushButton(Dialog)
        self.btnSend.setGeometry(QtCore.QRect(390, 520, 75, 23))
        self.btnSend.setObjectName("btnSend")
        self.btnRead = QtWidgets.QPushButton(Dialog)
        self.btnRead.setGeometry(QtCore.QRect(390, 550, 75, 23))
        self.btnRead.setObjectName("btnRead")
        self.led1 = LedWidget(Dialog)
        self.led1.setGeometry(QtCore.QRect(90, 120, 21, 21))
        self.led1.setObjectName("led1")
        self.led2 = LedWidget(Dialog)
        self.led2.setGeometry(QtCore.QRect(90, 140, 21, 21))
        self.led2.setObjectName("led2")
        self.led3 = LedWidget(Dialog)
        self.led3.setGeometry(QtCore.QRect(90, 160, 21, 21))
        self.led3.setObjectName("led3")
        self.led4 = LedWidget(Dialog)
        self.led4.setGeometry(QtCore.QRect(90, 180, 21, 21))
        self.led4.setObjectName("led4")
        self.led8 = LedWidget(Dialog)
        self.led8.setGeometry(QtCore.QRect(90, 220, 21, 21))
        self.led8.setObjectName("led8")
        self.led5 = LedWidget(Dialog)
        self.led5.setGeometry(QtCore.QRect(90, 200, 21, 21))
        self.led5.setObjectName("led5")
        self.led7 = LedWidget(Dialog)
        self.led7.setGeometry(QtCore.QRect(90, 260, 21, 21))
        self.led7.setObjectName("led7")
        self.led6 = LedWidget(Dialog)
        self.led6.setGeometry(QtCore.QRect(90, 240, 21, 21))
        self.led6.setObjectName("led6")
        self.lblBank3 = QtWidgets.QLabel(Dialog)
        self.lblBank3.setGeometry(QtCore.QRect(230, 100, 47, 13))
        self.lblBank3.setObjectName("lblBank3")
        self.lblBank4 = QtWidgets.QLabel(Dialog)
        self.lblBank4.setGeometry(QtCore.QRect(330, 100, 47, 13))
        self.lblBank4.setObjectName("lblBank4")
        self.lblBank2 = QtWidgets.QLabel(Dialog)
        self.lblBank2.setGeometry(QtCore.QRect(130, 100, 47, 13))
        self.lblBank2.setObjectName("lblBank2")
        self.lblBank1 = QtWidgets.QLabel(Dialog)
        self.lblBank1.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.lblBank1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lblBank1.setObjectName("lblBank1")
        self.K19 = QtWidgets.QCheckBox(Dialog)
        self.K19.setGeometry(QtCore.QRect(130, 160, 70, 17))
        self.K19.setObjectName("K19")
        self.led3_2 = LedWidget(Dialog)
        self.led3_2.setGeometry(QtCore.QRect(190, 160, 21, 21))
        self.led3_2.setObjectName("led3_2")
        self.led5_2 = LedWidget(Dialog)
        self.led5_2.setGeometry(QtCore.QRect(190, 200, 21, 21))
        self.led5_2.setObjectName("led5_2")
        self.ledb21 = LedWidget(Dialog)
        self.ledb21.setGeometry(QtCore.QRect(190, 120, 21, 21))
        self.ledb21.setObjectName("ledb21")
        self.K18 = QtWidgets.QCheckBox(Dialog)
        self.K18.setGeometry(QtCore.QRect(130, 140, 70, 17))
        self.K18.setObjectName("K18")
        self.K21 = QtWidgets.QCheckBox(Dialog)
        self.K21.setGeometry(QtCore.QRect(130, 200, 70, 17))
        self.K21.setObjectName("K21")
        self.K22 = QtWidgets.QCheckBox(Dialog)
        self.K22.setGeometry(QtCore.QRect(130, 220, 70, 17))
        self.K22.setObjectName("K22")
        self.led8_2 = LedWidget(Dialog)
        self.led8_2.setGeometry(QtCore.QRect(190, 220, 21, 21))
        self.led8_2.setObjectName("led8_2")
        self.led7_2 = LedWidget(Dialog)
        self.led7_2.setGeometry(QtCore.QRect(190, 260, 21, 21))
        self.led7_2.setObjectName("led7_2")
        self.K20 = QtWidgets.QCheckBox(Dialog)
        self.K20.setGeometry(QtCore.QRect(130, 180, 70, 17))
        self.K20.setObjectName("K20")
        self.K24 = QtWidgets.QCheckBox(Dialog)
        self.K24.setGeometry(QtCore.QRect(130, 260, 70, 17))
        self.K24.setObjectName("K24")
        self.K17 = QtWidgets.QCheckBox(Dialog)
        self.K17.setGeometry(QtCore.QRect(130, 120, 70, 17))
        self.K17.setObjectName("K17")
        self.led4_2 = LedWidget(Dialog)
        self.led4_2.setGeometry(QtCore.QRect(190, 180, 21, 21))
        self.led4_2.setObjectName("led4_2")
        self.K23 = QtWidgets.QCheckBox(Dialog)
        self.K23.setGeometry(QtCore.QRect(130, 240, 70, 17))
        self.K23.setObjectName("K23")
        self.led2_2 = LedWidget(Dialog)
        self.led2_2.setGeometry(QtCore.QRect(190, 140, 21, 21))
        self.led2_2.setObjectName("led2_2")
        self.led6_2 = LedWidget(Dialog)
        self.led6_2.setGeometry(QtCore.QRect(190, 240, 21, 21))
        self.led6_2.setObjectName("led6_2")
        self.led1_3 = LedWidget(Dialog)
        self.led1_3.setGeometry(QtCore.QRect(290, 120, 21, 21))
        self.led1_3.setObjectName("led1_3")
        self.led2_3 = LedWidget(Dialog)
        self.led2_3.setGeometry(QtCore.QRect(290, 140, 21, 21))
        self.led2_3.setObjectName("led2_3")
        self.K38 = QtWidgets.QCheckBox(Dialog)
        self.K38.setGeometry(QtCore.QRect(230, 220, 70, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K38.sizePolicy().hasHeightForWidth())
        self.K38.setSizePolicy(sizePolicy)
        self.K38.setObjectName("K38")
        self.led8_3 = LedWidget(Dialog)
        self.led8_3.setGeometry(QtCore.QRect(290, 220, 21, 21))
        self.led8_3.setObjectName("led8_3")
        self.led4_3 = LedWidget(Dialog)
        self.led4_3.setGeometry(QtCore.QRect(290, 180, 21, 21))
        self.led4_3.setObjectName("led4_3")
        self.K35 = QtWidgets.QCheckBox(Dialog)
        self.K35.setGeometry(QtCore.QRect(230, 160, 70, 17))
        self.K35.setObjectName("K35")
        self.K40 = QtWidgets.QCheckBox(Dialog)
        self.K40.setGeometry(QtCore.QRect(230, 260, 70, 17))
        self.K40.setObjectName("K40")
        self.led5_3 = LedWidget(Dialog)
        self.led5_3.setGeometry(QtCore.QRect(290, 200, 21, 21))
        self.led5_3.setObjectName("led5_3")
        self.led6_3 = LedWidget(Dialog)
        self.led6_3.setGeometry(QtCore.QRect(290, 240, 21, 21))
        self.led6_3.setObjectName("led6_3")
        self.K37 = QtWidgets.QCheckBox(Dialog)
        self.K37.setGeometry(QtCore.QRect(230, 200, 70, 17))
        self.K37.setObjectName("K37")
        self.led7_3 = LedWidget(Dialog)
        self.led7_3.setGeometry(QtCore.QRect(290, 260, 21, 21))
        self.led7_3.setObjectName("led7_3")
        self.led3_3 = LedWidget(Dialog)
        self.led3_3.setGeometry(QtCore.QRect(290, 160, 21, 21))
        self.led3_3.setObjectName("led3_3")
        self.K39 = QtWidgets.QCheckBox(Dialog)
        self.K39.setGeometry(QtCore.QRect(230, 240, 70, 17))
        self.K39.setObjectName("K39")
        self.K34 = QtWidgets.QCheckBox(Dialog)
        self.K34.setGeometry(QtCore.QRect(230, 140, 70, 17))
        self.K34.setObjectName("K34")
        self.K36 = QtWidgets.QCheckBox(Dialog)
        self.K36.setGeometry(QtCore.QRect(230, 180, 70, 17))
        self.K36.setObjectName("K36")
        self.K33 = QtWidgets.QCheckBox(Dialog)
        self.K33.setGeometry(QtCore.QRect(230, 120, 70, 17))
        self.K33.setObjectName("K33")
        self.K54 = QtWidgets.QCheckBox(Dialog)
        self.K54.setGeometry(QtCore.QRect(330, 220, 70, 17))
        self.K54.setObjectName("K54")
        self.led4_4 = LedWidget(Dialog)
        self.led4_4.setGeometry(QtCore.QRect(390, 180, 21, 21))
        self.led4_4.setObjectName("led4_4")
        self.led6_4 = LedWidget(Dialog)
        self.led6_4.setGeometry(QtCore.QRect(390, 240, 21, 21))
        self.led6_4.setObjectName("led6_4")
        self.led3_4 = LedWidget(Dialog)
        self.led3_4.setGeometry(QtCore.QRect(390, 160, 21, 21))
        self.led3_4.setObjectName("led3_4")
        self.K53 = QtWidgets.QCheckBox(Dialog)
        self.K53.setGeometry(QtCore.QRect(330, 200, 70, 17))
        self.K53.setObjectName("K53")
        self.K56 = QtWidgets.QCheckBox(Dialog)
        self.K56.setGeometry(QtCore.QRect(330, 260, 70, 17))
        self.K56.setObjectName("K56")
        self.led1_4 = LedWidget(Dialog)
        self.led1_4.setGeometry(QtCore.QRect(390, 120, 21, 21))
        self.led1_4.setObjectName("led1_4")
        self.led8_4 = LedWidget(Dialog)
        self.led8_4.setGeometry(QtCore.QRect(390, 220, 21, 21))
        self.led8_4.setObjectName("led8_4")
        self.K55 = QtWidgets.QCheckBox(Dialog)
        self.K55.setGeometry(QtCore.QRect(330, 240, 70, 17))
        self.K55.setObjectName("K55")
        self.led5_4 = LedWidget(Dialog)
        self.led5_4.setGeometry(QtCore.QRect(390, 200, 21, 21))
        self.led5_4.setObjectName("led5_4")
        self.K52 = QtWidgets.QCheckBox(Dialog)
        self.K52.setGeometry(QtCore.QRect(330, 180, 70, 17))
        self.K52.setObjectName("K52")
        self.K51 = QtWidgets.QCheckBox(Dialog)
        self.K51.setGeometry(QtCore.QRect(330, 160, 70, 17))
        self.K51.setObjectName("K51")
        self.led2_4 = LedWidget(Dialog)
        self.led2_4.setGeometry(QtCore.QRect(390, 140, 21, 21))
        self.led2_4.setObjectName("led2_4")
        self.led7_4 = LedWidget(Dialog)
        self.led7_4.setGeometry(QtCore.QRect(390, 260, 21, 21))
        self.led7_4.setObjectName("led7_4")
        self.K50 = QtWidgets.QCheckBox(Dialog)
        self.K50.setGeometry(QtCore.QRect(330, 140, 70, 17))
        self.K50.setObjectName("K50")
        self.K49 = QtWidgets.QCheckBox(Dialog)
        self.K49.setGeometry(QtCore.QRect(330, 120, 70, 17))
        self.K49.setObjectName("K49")
        self.chkSelectbank1 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank1.setGeometry(QtCore.QRect(30, 450, 91, 17))
        self.chkSelectbank1.setObjectName("chkSelectbank1")
        self.led3_5 = LedWidget(Dialog)
        self.led3_5.setGeometry(QtCore.QRect(90, 320, 21, 21))
        self.led3_5.setObjectName("led3_5")
        self.K1_2 = QtWidgets.QCheckBox(Dialog)
        self.K1_2.setGeometry(QtCore.QRect(30, 280, 70, 17))
        self.K1_2.setObjectName("K1_2")
        self.led2_5 = LedWidget(Dialog)
        self.led2_5.setGeometry(QtCore.QRect(90, 300, 21, 21))
        self.led2_5.setObjectName("led2_5")
        self.GPIO1_17 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_17.setGeometry(QtCore.QRect(30, 320, 70, 17))
        self.GPIO1_17.setObjectName("GPIO1_17")
        self.led8_5 = LedWidget(Dialog)
        self.led8_5.setGeometry(QtCore.QRect(90, 380, 21, 21))
        self.led8_5.setObjectName("led8_5")
        self.GPIO1_18 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_18.setGeometry(QtCore.QRect(30, 400, 70, 17))
        self.GPIO1_18.setObjectName("GPIO1_18")
        self.led4_5 = LedWidget(Dialog)
        self.led4_5.setGeometry(QtCore.QRect(90, 340, 21, 21))
        self.led4_5.setObjectName("led4_5")
        self.led7_5 = LedWidget(Dialog)
        self.led7_5.setGeometry(QtCore.QRect(90, 420, 21, 21))
        self.led7_5.setObjectName("led7_5")
        self.led5_5 = LedWidget(Dialog)
        self.led5_5.setGeometry(QtCore.QRect(90, 360, 21, 21))
        self.led5_5.setObjectName("led5_5")
        self.led6_5 = LedWidget(Dialog)
        self.led6_5.setGeometry(QtCore.QRect(90, 400, 21, 21))
        self.led6_5.setObjectName("led6_5")
        self.checkBox_22 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_22.setGeometry(QtCore.QRect(30, 340, 70, 17))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_23.setGeometry(QtCore.QRect(30, 380, 70, 17))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_24.setGeometry(QtCore.QRect(30, 420, 70, 17))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_25.setGeometry(QtCore.QRect(30, 300, 70, 17))
        self.checkBox_25.setObjectName("checkBox_25")
        self.GPIO1_19 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_19.setGeometry(QtCore.QRect(30, 360, 70, 17))
        self.GPIO1_19.setObjectName("GPIO1_19")
        self.led1_2 = LedWidget(Dialog)
        self.led1_2.setGeometry(QtCore.QRect(90, 280, 21, 21))
        self.led1_2.setObjectName("led1_2")
        self.led2_6 = LedWidget(Dialog)
        self.led2_6.setGeometry(QtCore.QRect(190, 300, 21, 21))
        self.led2_6.setObjectName("led2_6")
        self.K27 = QtWidgets.QCheckBox(Dialog)
        self.K27.setGeometry(QtCore.QRect(130, 320, 70, 17))
        self.K27.setObjectName("K27")
        self.K31 = QtWidgets.QCheckBox(Dialog)
        self.K31.setGeometry(QtCore.QRect(130, 400, 70, 17))
        self.K31.setObjectName("K31")
        self.K28 = QtWidgets.QCheckBox(Dialog)
        self.K28.setGeometry(QtCore.QRect(130, 340, 70, 17))
        self.K28.setObjectName("K28")
        self.K30 = QtWidgets.QCheckBox(Dialog)
        self.K30.setGeometry(QtCore.QRect(130, 380, 70, 17))
        self.K30.setObjectName("K30")
        self.led6_6 = LedWidget(Dialog)
        self.led6_6.setGeometry(QtCore.QRect(190, 400, 21, 21))
        self.led6_6.setObjectName("led6_6")
        self.K26 = QtWidgets.QCheckBox(Dialog)
        self.K26.setGeometry(QtCore.QRect(130, 300, 70, 17))
        self.K26.setObjectName("K26")
        self.led4_6 = LedWidget(Dialog)
        self.led4_6.setGeometry(QtCore.QRect(190, 340, 21, 21))
        self.led4_6.setObjectName("led4_6")
        self.led3_6 = LedWidget(Dialog)
        self.led3_6.setGeometry(QtCore.QRect(190, 320, 21, 21))
        self.led3_6.setObjectName("led3_6")
        self.chkSelectbank2 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank2.setGeometry(QtCore.QRect(130, 450, 91, 17))
        self.chkSelectbank2.setObjectName("chkSelectbank2")
        self.led5_6 = LedWidget(Dialog)
        self.led5_6.setGeometry(QtCore.QRect(190, 360, 21, 21))
        self.led5_6.setObjectName("led5_6")
        self.K25 = QtWidgets.QCheckBox(Dialog)
        self.K25.setGeometry(QtCore.QRect(130, 280, 70, 17))
        self.K25.setObjectName("K25")
        self.led8_6 = LedWidget(Dialog)
        self.led8_6.setGeometry(QtCore.QRect(190, 380, 21, 21))
        self.led8_6.setObjectName("led8_6")
        self.led7_6 = LedWidget(Dialog)
        self.led7_6.setGeometry(QtCore.QRect(190, 420, 21, 21))
        self.led7_6.setObjectName("led7_6")
        self.K32 = QtWidgets.QCheckBox(Dialog)
        self.K32.setGeometry(QtCore.QRect(130, 420, 70, 17))
        self.K32.setObjectName("K32")
        self.K29 = QtWidgets.QCheckBox(Dialog)
        self.K29.setGeometry(QtCore.QRect(130, 360, 70, 17))
        self.K29.setObjectName("K29")
        self.led1_5 = LedWidget(Dialog)
        self.led1_5.setGeometry(QtCore.QRect(190, 280, 21, 21))
        self.led1_5.setObjectName("led1_5")
        self.led2_7 = LedWidget(Dialog)
        self.led2_7.setGeometry(QtCore.QRect(290, 300, 21, 21))
        self.led2_7.setObjectName("led2_7")
        self.K43 = QtWidgets.QCheckBox(Dialog)
        self.K43.setGeometry(QtCore.QRect(230, 320, 70, 17))
        self.K43.setObjectName("K43")
        self.K47 = QtWidgets.QCheckBox(Dialog)
        self.K47.setGeometry(QtCore.QRect(230, 400, 70, 17))
        self.K47.setMouseTracking(True)
        self.K47.setObjectName("K47")
        self.K44 = QtWidgets.QCheckBox(Dialog)
        self.K44.setGeometry(QtCore.QRect(230, 340, 70, 17))
        self.K44.setObjectName("K44")
        self.K46 = QtWidgets.QCheckBox(Dialog)
        self.K46.setGeometry(QtCore.QRect(230, 380, 70, 17))
        self.K46.setObjectName("K46")
        self.led6_7 = LedWidget(Dialog)
        self.led6_7.setGeometry(QtCore.QRect(290, 400, 21, 21))
        self.led6_7.setObjectName("led6_7")
        self.K42 = QtWidgets.QCheckBox(Dialog)
        self.K42.setGeometry(QtCore.QRect(230, 300, 70, 17))
        self.K42.setObjectName("K42")
        self.led4_7 = LedWidget(Dialog)
        self.led4_7.setGeometry(QtCore.QRect(290, 340, 21, 21))
        self.led4_7.setObjectName("led4_7")
        self.led3_7 = LedWidget(Dialog)
        self.led3_7.setGeometry(QtCore.QRect(290, 320, 21, 21))
        self.led3_7.setObjectName("led3_7")
        self.chkSelectbank3 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank3.setGeometry(QtCore.QRect(230, 450, 91, 17))
        self.chkSelectbank3.setObjectName("chkSelectbank3")
        self.led5_7 = LedWidget(Dialog)
        self.led5_7.setGeometry(QtCore.QRect(290, 360, 21, 21))
        self.led5_7.setObjectName("led5_7")
        self.K41 = QtWidgets.QCheckBox(Dialog)
        self.K41.setGeometry(QtCore.QRect(230, 280, 70, 17))
        self.K41.setObjectName("K41")
        self.led8_7 = LedWidget(Dialog)
        self.led8_7.setGeometry(QtCore.QRect(290, 380, 21, 21))
        self.led8_7.setObjectName("led8_7")
        self.led7_7 = LedWidget(Dialog)
        self.led7_7.setGeometry(QtCore.QRect(290, 420, 21, 21))
        self.led7_7.setObjectName("led7_7")
        self.K48 = QtWidgets.QCheckBox(Dialog)
        self.K48.setGeometry(QtCore.QRect(230, 420, 70, 17))
        self.K48.setObjectName("K48")
        self.K45 = QtWidgets.QCheckBox(Dialog)
        self.K45.setGeometry(QtCore.QRect(230, 360, 70, 17))
        self.K45.setObjectName("K45")
        self.led1_6 = LedWidget(Dialog)
        self.led1_6.setGeometry(QtCore.QRect(290, 280, 21, 21))
        self.led1_6.setObjectName("led1_6")
        self.led2_8 = LedWidget(Dialog)
        self.led2_8.setGeometry(QtCore.QRect(390, 300, 21, 21))
        self.led2_8.setObjectName("led2_8")
        self.K59 = QtWidgets.QCheckBox(Dialog)
        self.K59.setGeometry(QtCore.QRect(330, 320, 70, 17))
        self.K59.setObjectName("K59")
        self.K63 = QtWidgets.QCheckBox(Dialog)
        self.K63.setGeometry(QtCore.QRect(330, 400, 70, 17))
        self.K63.setObjectName("K63")
        self.K60 = QtWidgets.QCheckBox(Dialog)
        self.K60.setGeometry(QtCore.QRect(330, 340, 70, 17))
        self.K60.setObjectName("K60")
        self.K62 = QtWidgets.QCheckBox(Dialog)
        self.K62.setGeometry(QtCore.QRect(330, 380, 70, 17))
        self.K62.setObjectName("K62")
        self.led6_8 = LedWidget(Dialog)
        self.led6_8.setGeometry(QtCore.QRect(390, 400, 21, 21))
        self.led6_8.setObjectName("led6_8")
        self.K58 = QtWidgets.QCheckBox(Dialog)
        self.K58.setGeometry(QtCore.QRect(330, 300, 70, 17))
        self.K58.setObjectName("K58")
        self.led4_8 = LedWidget(Dialog)
        self.led4_8.setGeometry(QtCore.QRect(390, 340, 21, 21))
        self.led4_8.setObjectName("led4_8")
        self.led3_8 = LedWidget(Dialog)
        self.led3_8.setGeometry(QtCore.QRect(390, 320, 21, 21))
        self.led3_8.setObjectName("led3_8")
        self.chkSelectbank4 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank4.setGeometry(QtCore.QRect(330, 450, 91, 17))
        self.chkSelectbank4.setObjectName("chkSelectbank4")
        self.led5_8 = LedWidget(Dialog)
        self.led5_8.setGeometry(QtCore.QRect(390, 360, 21, 21))
        self.led5_8.setObjectName("led5_8")
        self.K57 = QtWidgets.QCheckBox(Dialog)
        self.K57.setGeometry(QtCore.QRect(330, 280, 70, 17))
        self.K57.setObjectName("K57")
        self.led8_8 = LedWidget(Dialog)
        self.led8_8.setGeometry(QtCore.QRect(390, 380, 21, 21))
        self.led8_8.setObjectName("led8_8")
        self.led7_8 = LedWidget(Dialog)
        self.led7_8.setGeometry(QtCore.QRect(390, 420, 21, 21))
        self.led7_8.setObjectName("led7_8")
        self.K64 = QtWidgets.QCheckBox(Dialog)
        self.K64.setGeometry(QtCore.QRect(330, 420, 70, 17))
        self.K64.setObjectName("K64")
        self.K61 = QtWidgets.QCheckBox(Dialog)
        self.K61.setGeometry(QtCore.QRect(330, 360, 70, 17))
        self.K61.setObjectName("K61")
        self.led1_7 = LedWidget(Dialog)
        self.led1_7.setGeometry(QtCore.QRect(390, 280, 21, 21))
        self.led1_7.setObjectName("led1_7")
        self.K51.raise_()
        self.K1_2.raise_()
        self.txtIP.raise_()
        self.K1.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.GPIO1_2.raise_()
        self.checkBox_4.raise_()
        self.GPIO1_3.raise_()
        self.GPIO1_4.raise_()
        self.checkBox_5.raise_()
        self.label.raise_()
        self.txtSend.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.txtRead.raise_()
        self.label_4.raise_()
        self.plainTextEdit_4.raise_()
        self.btnConnect.raise_()
        self.txtPORT.raise_()
        self.label_5.raise_()
        self.btnSend.raise_()
        self.btnRead.raise_()
        self.led1.raise_()
        self.led2.raise_()
        self.led3.raise_()
        self.led4.raise_()
        self.led8.raise_()
        self.led5.raise_()
        self.led7.raise_()
        self.led6.raise_()
        self.lblBank3.raise_()
        self.lblBank4.raise_()
        self.lblBank2.raise_()
        self.lblBank1.raise_()
        self.K19.raise_()
        self.led3_2.raise_()
        self.led5_2.raise_()
        self.ledb21.raise_()
        self.K18.raise_()
        self.K21.raise_()
        self.K22.raise_()
        self.led8_2.raise_()
        self.led7_2.raise_()
        self.K20.raise_()
        self.K24.raise_()
        self.K17.raise_()
        self.led4_2.raise_()
        self.K23.raise_()
        self.led2_2.raise_()
        self.led6_2.raise_()
        self.led1_3.raise_()
        self.led2_3.raise_()
        self.K38.raise_()
        self.led8_3.raise_()
        self.led4_3.raise_()
        self.K35.raise_()
        self.K40.raise_()
        self.led5_3.raise_()
        self.led6_3.raise_()
        self.K37.raise_()
        self.led7_3.raise_()
        self.led3_3.raise_()
        self.K39.raise_()
        self.K34.raise_()
        self.K36.raise_()
        self.K33.raise_()
        self.K54.raise_()
        self.led4_4.raise_()
        self.led6_4.raise_()
        self.led3_4.raise_()
        self.K53.raise_()
        self.K56.raise_()
        self.led1_4.raise_()
        self.led8_4.raise_()
        self.K55.raise_()
        self.led5_4.raise_()
        self.K52.raise_()
        self.led2_4.raise_()
        self.led7_4.raise_()
        self.K50.raise_()
        self.K49.raise_()
        self.chkSelectbank1.raise_()
        self.led3_5.raise_()
        self.led2_5.raise_()
        self.GPIO1_17.raise_()
        self.led8_5.raise_()
        self.GPIO1_18.raise_()
        self.led4_5.raise_()
        self.led7_5.raise_()
        self.led5_5.raise_()
        self.led6_5.raise_()
        self.checkBox_22.raise_()
        self.checkBox_23.raise_()
        self.checkBox_24.raise_()
        self.checkBox_25.raise_()
        self.GPIO1_19.raise_()
        self.led1_2.raise_()
        self.led2_6.raise_()
        self.K27.raise_()
        self.K31.raise_()
        self.K28.raise_()
        self.K30.raise_()
        self.led6_6.raise_()
        self.K26.raise_()
        self.led4_6.raise_()
        self.led3_6.raise_()
        self.chkSelectbank2.raise_()
        self.led5_6.raise_()
        self.K25.raise_()
        self.led8_6.raise_()
        self.led7_6.raise_()
        self.K32.raise_()
        self.K29.raise_()
        self.led1_5.raise_()
        self.led2_7.raise_()
        self.K43.raise_()
        self.K47.raise_()
        self.K44.raise_()
        self.K46.raise_()
        self.led6_7.raise_()
        self.K42.raise_()
        self.led4_7.raise_()
        self.led3_7.raise_()
        self.chkSelectbank3.raise_()
        self.led5_7.raise_()
        self.K41.raise_()
        self.led8_7.raise_()
        self.led7_7.raise_()
        self.K48.raise_()
        self.K45.raise_()
        self.led1_6.raise_()
        self.led2_8.raise_()
        self.K59.raise_()
        self.K63.raise_()
        self.K60.raise_()
        self.K62.raise_()
        self.led6_8.raise_()
        self.K58.raise_()
        self.led4_8.raise_()
        self.led3_8.raise_()
        self.chkSelectbank4.raise_()
        self.led5_8.raise_()
        self.K57.raise_()
        self.led8_8.raise_()
        self.led7_8.raise_()
        self.K64.raise_()
        self.K61.raise_()
        self.led1_7.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.K1.setText(_translate("Dialog", "K1"))
        self.checkBox_2.setText(_translate("Dialog", "K2"))
        self.checkBox_3.setText(_translate("Dialog", "K4"))
        self.GPIO1_2.setText(_translate("Dialog", "K3"))
        self.checkBox_4.setText(_translate("Dialog", "K6"))
        self.GPIO1_3.setText(_translate("Dialog", "K7"))
        self.GPIO1_4.setText(_translate("Dialog", "K5"))
        self.checkBox_5.setText(_translate("Dialog", "K8"))
        self.label.setText(_translate("Dialog", "IP"))
        self.label_2.setText(_translate("Dialog", "Write"))
        self.label_3.setText(_translate("Dialog", "Read"))
        self.label_4.setText(_translate("Dialog", "Address"))
        self.btnConnect.setText(_translate("Dialog", "Connect"))
        self.label_5.setText(_translate("Dialog", "PORT"))
        self.btnSend.setText(_translate("Dialog", "Send"))
        self.btnRead.setText(_translate("Dialog", "Read"))
        self.lblBank3.setText(_translate("Dialog", "BANK 3"))
        self.lblBank4.setText(_translate("Dialog", "BANK 4"))
        self.lblBank2.setText(_translate("Dialog", "BANK 2"))
        self.lblBank1.setText(_translate("Dialog", "BANK 1"))
        self.K19.setText(_translate("Dialog", "K19"))
        self.K18.setText(_translate("Dialog", "K18"))
        self.K21.setText(_translate("Dialog", "K21"))
        self.K22.setText(_translate("Dialog", "K22"))
        self.K20.setText(_translate("Dialog", "K20"))
        self.K24.setText(_translate("Dialog", "K24"))
        self.K17.setText(_translate("Dialog", "K17"))
        self.K23.setText(_translate("Dialog", "K23"))
        self.K38.setText(_translate("Dialog", "K38"))
        self.K35.setText(_translate("Dialog", "K35"))
        self.K40.setText(_translate("Dialog", "K40"))
        self.K37.setText(_translate("Dialog", "K37"))
        self.K39.setText(_translate("Dialog", "K39"))
        self.K34.setText(_translate("Dialog", "K34"))
        self.K36.setText(_translate("Dialog", "K36"))
        self.K33.setText(_translate("Dialog", "K33"))
        self.K54.setText(_translate("Dialog", "K54"))
        self.K53.setText(_translate("Dialog", "K53"))
        self.K56.setText(_translate("Dialog", "K56"))
        self.K55.setText(_translate("Dialog", "K55"))
        self.K52.setText(_translate("Dialog", "K52"))
        self.K51.setText(_translate("Dialog", "K51"))
        self.K50.setText(_translate("Dialog", "K50"))
        self.K49.setText(_translate("Dialog", "K49"))
        self.chkSelectbank1.setText(_translate("Dialog", "Select Bank 1"))
        self.K1_2.setText(_translate("Dialog", "K9"))
        self.GPIO1_17.setText(_translate("Dialog", "K11"))
        self.GPIO1_18.setText(_translate("Dialog", "K15"))
        self.checkBox_22.setText(_translate("Dialog", "K12"))
        self.checkBox_23.setText(_translate("Dialog", "K14"))
        self.checkBox_24.setText(_translate("Dialog", "K16"))
        self.checkBox_25.setText(_translate("Dialog", "K10"))
        self.GPIO1_19.setText(_translate("Dialog", "K13"))
        self.K27.setText(_translate("Dialog", "K27"))
        self.K31.setText(_translate("Dialog", "K31"))
        self.K28.setText(_translate("Dialog", "K28"))
        self.K30.setText(_translate("Dialog", "K30"))
        self.K26.setText(_translate("Dialog", "K26"))
        self.chkSelectbank2.setText(_translate("Dialog", "Select Bank 2"))
        self.K25.setText(_translate("Dialog", "K25"))
        self.K32.setText(_translate("Dialog", "K32"))
        self.K29.setText(_translate("Dialog", "K29"))
        self.K43.setText(_translate("Dialog", "K43"))
        self.K47.setText(_translate("Dialog", "K47"))
        self.K44.setText(_translate("Dialog", "K44"))
        self.K46.setText(_translate("Dialog", "K46"))
        self.K42.setText(_translate("Dialog", "K42"))
        self.chkSelectbank3.setText(_translate("Dialog", "Select Bank 3"))
        self.K41.setText(_translate("Dialog", "K41"))
        self.K48.setText(_translate("Dialog", "K48"))
        self.K45.setText(_translate("Dialog", "K45"))
        self.K59.setText(_translate("Dialog", "K59"))
        self.K63.setText(_translate("Dialog", "K63"))
        self.K60.setText(_translate("Dialog", "K60"))
        self.K62.setText(_translate("Dialog", "K62"))
        self.K58.setText(_translate("Dialog", "K58"))
        self.chkSelectbank4.setText(_translate("Dialog", "Select Bank 4"))
        self.K57.setText(_translate("Dialog", "K57"))
        self.K64.setText(_translate("Dialog", "K64"))
        self.K61.setText(_translate("Dialog", "K61"))

from ledwidget import LedWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

