# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpio_gui_thrc.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#import ledcontrol

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(454, 563)
        self.K1 = QtWidgets.QCheckBox(Dialog)
        self.K1.setGeometry(QtCore.QRect(30, 110, 70, 17))
        self.K1.setObjectName("K1")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 130, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 170, 70, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.GPIO1_2 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_2.setGeometry(QtCore.QRect(30, 150, 70, 17))
        self.GPIO1_2.setObjectName("GPIO1_2")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 210, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.GPIO1_3 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_3.setGeometry(QtCore.QRect(30, 230, 70, 17))
        self.GPIO1_3.setObjectName("GPIO1_3")
        self.GPIO1_4 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_4.setGeometry(QtCore.QRect(30, 190, 70, 17))
        self.GPIO1_4.setObjectName("GPIO1_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 250, 70, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.lblboardid = QtWidgets.QLabel(Dialog)
        self.lblboardid.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.lblboardid.setObjectName("lblboardid")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(110, 60, 131, 21))
        self.plainTextEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.led1 = LedWidget(Dialog)
        self.led1.setGeometry(QtCore.QRect(90, 110, 21, 21))
        self.led1.setObjectName("led1")
        self.led1.setDiameter(15.0);
        self.led2 = LedWidget(Dialog)
        self.led2.setGeometry(QtCore.QRect(90, 130, 21, 21))
        self.led2.setObjectName("led2")
        self.led3 = LedWidget(Dialog)
        self.led3.setGeometry(QtCore.QRect(90, 150, 21, 21))
        self.led3.setObjectName("led3")
        self.led4 = LedWidget(Dialog)
        self.led4.setGeometry(QtCore.QRect(90, 170, 21, 21))
        self.led4.setObjectName("led4")
        self.led6 = LedWidget(Dialog)
        self.led6.setGeometry(QtCore.QRect(90, 210, 21, 21))
        self.led6.setObjectName("led6")
        self.led5 = LedWidget(Dialog)
        self.led5.setGeometry(QtCore.QRect(90, 190, 21, 21))
        self.led5.setObjectName("led5")
        self.led8 = LedWidget(Dialog)
        self.led8.setGeometry(QtCore.QRect(90, 250, 21, 21))
        self.led8.setObjectName("led8")
        self.led7 = LedWidget(Dialog)
        self.led7.setGeometry(QtCore.QRect(90, 230, 21, 21))
        self.led7.setObjectName("led7")
        self.lblBank3 = QtWidgets.QLabel(Dialog)
        self.lblBank3.setGeometry(QtCore.QRect(230, 90, 47, 13))
        self.lblBank3.setObjectName("lblBank3")
        self.lblBank4 = QtWidgets.QLabel(Dialog)
        self.lblBank4.setGeometry(QtCore.QRect(330, 90, 47, 13))
        self.lblBank4.setObjectName("lblBank4")
        self.lblBank2 = QtWidgets.QLabel(Dialog)
        self.lblBank2.setGeometry(QtCore.QRect(130, 90, 47, 13))
        self.lblBank2.setObjectName("lblBank2")
        self.lblBank1 = QtWidgets.QLabel(Dialog)
        self.lblBank1.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.lblBank1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lblBank1.setObjectName("lblBank1")
        self.K19 = QtWidgets.QCheckBox(Dialog)
        self.K19.setGeometry(QtCore.QRect(130, 150, 70, 17))
        self.K19.setObjectName("K19")
        self.led19 = LedWidget(Dialog)
        self.led19.setGeometry(QtCore.QRect(190, 150, 21, 21))
        self.led19.setObjectName("led19")
        self.led21 = LedWidget(Dialog)
        self.led21.setGeometry(QtCore.QRect(190, 190, 21, 21))
        self.led21.setObjectName("led21")
        self.led17 = LedWidget(Dialog)
        self.led17.setGeometry(QtCore.QRect(190, 110, 21, 21))
        self.led17.setObjectName("led17")
        self.K18 = QtWidgets.QCheckBox(Dialog)
        self.K18.setGeometry(QtCore.QRect(130, 130, 70, 17))
        self.K18.setObjectName("K18")
        self.K21 = QtWidgets.QCheckBox(Dialog)
        self.K21.setGeometry(QtCore.QRect(130, 190, 70, 17))
        self.K21.setObjectName("K21")
        self.K22 = QtWidgets.QCheckBox(Dialog)
        self.K22.setGeometry(QtCore.QRect(130, 210, 70, 17))
        self.K22.setObjectName("K22")
        self.led22 = LedWidget(Dialog)
        self.led22.setGeometry(QtCore.QRect(190, 210, 21, 21))
        self.led22.setObjectName("led22")
        self.led24 = LedWidget(Dialog)
        self.led24.setGeometry(QtCore.QRect(190, 250, 21, 21))
        self.led24.setObjectName("led24")
        self.K20 = QtWidgets.QCheckBox(Dialog)
        self.K20.setGeometry(QtCore.QRect(130, 170, 70, 17))
        self.K20.setObjectName("K20")
        self.K24 = QtWidgets.QCheckBox(Dialog)
        self.K24.setGeometry(QtCore.QRect(130, 250, 70, 17))
        self.K24.setObjectName("K24")
        self.K17 = QtWidgets.QCheckBox(Dialog)
        self.K17.setGeometry(QtCore.QRect(130, 110, 70, 17))
        self.K17.setObjectName("K17")
        self.led20 = LedWidget(Dialog)
        self.led20.setGeometry(QtCore.QRect(190, 170, 21, 21))
        self.led20.setObjectName("led20")
        self.K23 = QtWidgets.QCheckBox(Dialog)
        self.K23.setGeometry(QtCore.QRect(130, 230, 70, 17))
        self.K23.setObjectName("K23")
        self.led18 = LedWidget(Dialog)
        self.led18.setGeometry(QtCore.QRect(190, 130, 21, 21))
        self.led18.setObjectName("led18")
        self.led23 = LedWidget(Dialog)
        self.led23.setGeometry(QtCore.QRect(190, 230, 21, 21))
        self.led23.setObjectName("led23")
        self.led33 = LedWidget(Dialog)
        self.led33.setGeometry(QtCore.QRect(290, 110, 21, 21))
        self.led33.setObjectName("led33")
        self.led34 = LedWidget(Dialog)
        self.led34.setGeometry(QtCore.QRect(290, 130, 21, 21))
        self.led34.setObjectName("led34")
        self.K38 = QtWidgets.QCheckBox(Dialog)
        self.K38.setGeometry(QtCore.QRect(230, 210, 70, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K38.sizePolicy().hasHeightForWidth())
        self.K38.setSizePolicy(sizePolicy)
        self.K38.setObjectName("K38")
        self.led38 = LedWidget(Dialog)
        self.led38.setGeometry(QtCore.QRect(290, 210, 21, 21))
        self.led38.setObjectName("led38")
        self.led36 = LedWidget(Dialog)
        self.led36.setGeometry(QtCore.QRect(290, 170, 21, 21))
        self.led36.setObjectName("led36")
        self.K35 = QtWidgets.QCheckBox(Dialog)
        self.K35.setGeometry(QtCore.QRect(230, 150, 70, 17))
        self.K35.setObjectName("K35")
        self.K40 = QtWidgets.QCheckBox(Dialog)
        self.K40.setGeometry(QtCore.QRect(230, 250, 70, 17))
        self.K40.setObjectName("K40")
        self.led37 = LedWidget(Dialog)
        self.led37.setGeometry(QtCore.QRect(290, 190, 21, 21))
        self.led37.setObjectName("led37")
        self.led39 = LedWidget(Dialog)
        self.led39.setGeometry(QtCore.QRect(290, 230, 21, 21))
        self.led39.setObjectName("led39")
        self.K37 = QtWidgets.QCheckBox(Dialog)
        self.K37.setGeometry(QtCore.QRect(230, 190, 70, 17))
        self.K37.setObjectName("K37")
        self.led40 = LedWidget(Dialog)
        self.led40.setGeometry(QtCore.QRect(290, 250, 21, 21))
        self.led40.setObjectName("led40")
        self.led35 = LedWidget(Dialog)
        self.led35.setGeometry(QtCore.QRect(290, 150, 21, 21))
        self.led35.setObjectName("led35")
        self.K39 = QtWidgets.QCheckBox(Dialog)
        self.K39.setGeometry(QtCore.QRect(230, 230, 70, 17))
        self.K39.setObjectName("K39")
        self.K34 = QtWidgets.QCheckBox(Dialog)
        self.K34.setGeometry(QtCore.QRect(230, 130, 70, 17))
        self.K34.setObjectName("K34")
        self.K36 = QtWidgets.QCheckBox(Dialog)
        self.K36.setGeometry(QtCore.QRect(230, 170, 70, 17))
        self.K36.setObjectName("K36")
        self.K33 = QtWidgets.QCheckBox(Dialog)
        self.K33.setGeometry(QtCore.QRect(230, 110, 70, 17))
        self.K33.setObjectName("K33")
        self.K54 = QtWidgets.QCheckBox(Dialog)
        self.K54.setGeometry(QtCore.QRect(330, 210, 70, 17))
        self.K54.setObjectName("K54")
        self.led51_2 = LedWidget(Dialog)
        self.led51_2.setGeometry(QtCore.QRect(390, 170, 21, 21))
        self.led51_2.setObjectName("led51_2")
        self.led55 = LedWidget(Dialog)
        self.led55.setGeometry(QtCore.QRect(390, 230, 21, 21))
        self.led55.setObjectName("led55")
        self.led51 = LedWidget(Dialog)
        self.led51.setGeometry(QtCore.QRect(390, 150, 21, 21))
        self.led51.setObjectName("led51")
        self.K53 = QtWidgets.QCheckBox(Dialog)
        self.K53.setGeometry(QtCore.QRect(330, 190, 70, 17))
        self.K53.setObjectName("K53")
        self.K56 = QtWidgets.QCheckBox(Dialog)
        self.K56.setGeometry(QtCore.QRect(330, 250, 70, 17))
        self.K56.setObjectName("K56")
        self.led49 = LedWidget(Dialog)
        self.led49.setGeometry(QtCore.QRect(390, 110, 21, 21))
        self.led49.setObjectName("led49")
        self.led54 = LedWidget(Dialog)
        self.led54.setGeometry(QtCore.QRect(390, 210, 21, 21))
        self.led54.setObjectName("led54")
        self.K55 = QtWidgets.QCheckBox(Dialog)
        self.K55.setGeometry(QtCore.QRect(330, 230, 70, 17))
        self.K55.setObjectName("K55")
        self.led53 = LedWidget(Dialog)
        self.led53.setGeometry(QtCore.QRect(390, 190, 21, 21))
        self.led53.setObjectName("led53")
        self.K52 = QtWidgets.QCheckBox(Dialog)
        self.K52.setGeometry(QtCore.QRect(330, 170, 70, 17))
        self.K52.setObjectName("K52")
        self.K51 = QtWidgets.QCheckBox(Dialog)
        self.K51.setGeometry(QtCore.QRect(330, 150, 70, 17))
        self.K51.setObjectName("K51")
        self.led50 = LedWidget(Dialog)
        self.led50.setGeometry(QtCore.QRect(390, 130, 21, 21))
        self.led50.setObjectName("led50")
        self.led56 = LedWidget(Dialog)
        self.led56.setGeometry(QtCore.QRect(390, 250, 21, 21))
        self.led56.setObjectName("led56")
        self.K50 = QtWidgets.QCheckBox(Dialog)
        self.K50.setGeometry(QtCore.QRect(330, 130, 70, 17))
        self.K50.setObjectName("K50")
        self.K49 = QtWidgets.QCheckBox(Dialog)
        self.K49.setGeometry(QtCore.QRect(330, 110, 70, 17))
        self.K49.setObjectName("K49")
        self.chkSelectbank1 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank1.setGeometry(QtCore.QRect(30, 440, 91, 17))
        self.chkSelectbank1.setObjectName("chkSelectbank1")
        self.led11 = LedWidget(Dialog)
        self.led11.setGeometry(QtCore.QRect(90, 310, 21, 21))
        self.led11.setObjectName("led11")
        self.K1_2 = QtWidgets.QCheckBox(Dialog)
        self.K1_2.setGeometry(QtCore.QRect(30, 270, 70, 17))
        self.K1_2.setObjectName("K1_2")
        self.led10 = LedWidget(Dialog)
        self.led10.setGeometry(QtCore.QRect(90, 290, 21, 21))
        self.led10.setObjectName("led10")
        self.GPIO1_17 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_17.setGeometry(QtCore.QRect(30, 310, 70, 17))
        self.GPIO1_17.setObjectName("GPIO1_17")
        self.led14 = LedWidget(Dialog)
        self.led14.setGeometry(QtCore.QRect(90, 370, 21, 21))
        self.led14.setObjectName("led14")
        self.GPIO1_18 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_18.setGeometry(QtCore.QRect(30, 390, 70, 17))
        self.GPIO1_18.setObjectName("GPIO1_18")
        self.led12 = LedWidget(Dialog)
        self.led12.setGeometry(QtCore.QRect(90, 330, 21, 21))
        self.led12.setObjectName("led12")
        self.led16 = LedWidget(Dialog)
        self.led16.setGeometry(QtCore.QRect(90, 410, 21, 21))
        self.led16.setObjectName("led16")
        self.led13 = LedWidget(Dialog)
        self.led13.setGeometry(QtCore.QRect(90, 350, 21, 21))
        self.led13.setObjectName("led13")
        self.led15 = LedWidget(Dialog)
        self.led15.setGeometry(QtCore.QRect(90, 390, 21, 21))
        self.led15.setObjectName("led15")
        self.checkBox_22 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_22.setGeometry(QtCore.QRect(30, 330, 70, 17))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_23.setGeometry(QtCore.QRect(30, 370, 70, 17))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_24.setGeometry(QtCore.QRect(30, 410, 70, 17))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_25.setGeometry(QtCore.QRect(30, 290, 70, 17))
        self.checkBox_25.setObjectName("checkBox_25")
        self.GPIO1_19 = QtWidgets.QCheckBox(Dialog)
        self.GPIO1_19.setGeometry(QtCore.QRect(30, 350, 70, 17))
        self.GPIO1_19.setObjectName("GPIO1_19")
        self.led9 = LedWidget(Dialog)
        self.led9.setGeometry(QtCore.QRect(90, 270, 21, 21))
        self.led9.setObjectName("led9")
        self.led26 = LedWidget(Dialog)
        self.led26.setGeometry(QtCore.QRect(190, 290, 21, 21))
        self.led26.setObjectName("led26")
        self.K27 = QtWidgets.QCheckBox(Dialog)
        self.K27.setGeometry(QtCore.QRect(130, 310, 70, 17))
        self.K27.setObjectName("K27")
        self.K31 = QtWidgets.QCheckBox(Dialog)
        self.K31.setGeometry(QtCore.QRect(130, 390, 70, 17))
        self.K31.setObjectName("K31")
        self.K28 = QtWidgets.QCheckBox(Dialog)
        self.K28.setGeometry(QtCore.QRect(130, 330, 70, 17))
        self.K28.setObjectName("K28")
        self.K30 = QtWidgets.QCheckBox(Dialog)
        self.K30.setGeometry(QtCore.QRect(130, 370, 70, 17))
        self.K30.setObjectName("K30")
        self.led31 = LedWidget(Dialog)
        self.led31.setGeometry(QtCore.QRect(190, 390, 21, 21))
        self.led31.setObjectName("led31")
        self.K26 = QtWidgets.QCheckBox(Dialog)
        self.K26.setGeometry(QtCore.QRect(130, 290, 70, 17))
        self.K26.setObjectName("K26")
        self.led28 = LedWidget(Dialog)
        self.led28.setGeometry(QtCore.QRect(190, 330, 21, 21))
        self.led28.setObjectName("led28")
        self.led27 = LedWidget(Dialog)
        self.led27.setGeometry(QtCore.QRect(190, 310, 21, 21))
        self.led27.setObjectName("led27")
        self.chkSelectbank2 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank2.setGeometry(QtCore.QRect(130, 440, 91, 17))
        self.chkSelectbank2.setObjectName("chkSelectbank2")
        self.led29 = LedWidget(Dialog)
        self.led29.setGeometry(QtCore.QRect(190, 350, 21, 21))
        self.led29.setObjectName("led29")
        self.K25 = QtWidgets.QCheckBox(Dialog)
        self.K25.setGeometry(QtCore.QRect(130, 270, 70, 17))
        self.K25.setObjectName("K25")
        self.led30 = LedWidget(Dialog)
        self.led30.setGeometry(QtCore.QRect(190, 370, 21, 21))
        self.led30.setObjectName("led30")
        self.led32 = LedWidget(Dialog)
        self.led32.setGeometry(QtCore.QRect(190, 410, 21, 21))
        self.led32.setObjectName("led32")
        self.K32 = QtWidgets.QCheckBox(Dialog)
        self.K32.setGeometry(QtCore.QRect(130, 410, 70, 17))
        self.K32.setObjectName("K32")
        self.K29 = QtWidgets.QCheckBox(Dialog)
        self.K29.setGeometry(QtCore.QRect(130, 350, 70, 17))
        self.K29.setObjectName("K29")
        self.led25 = LedWidget(Dialog)
        self.led25.setGeometry(QtCore.QRect(190, 270, 21, 21))
        self.led25.setObjectName("led25")
        self.led42 = LedWidget(Dialog)
        self.led42.setGeometry(QtCore.QRect(290, 290, 21, 21))
        self.led42.setObjectName("led42")
        self.K43 = QtWidgets.QCheckBox(Dialog)
        self.K43.setGeometry(QtCore.QRect(230, 310, 70, 17))
        self.K43.setObjectName("K43")
        self.K47 = QtWidgets.QCheckBox(Dialog)
        self.K47.setGeometry(QtCore.QRect(230, 390, 70, 17))
        self.K47.setMouseTracking(True)
        self.K47.setObjectName("K47")
        self.K44 = QtWidgets.QCheckBox(Dialog)
        self.K44.setGeometry(QtCore.QRect(230, 330, 70, 17))
        self.K44.setObjectName("K44")
        self.K46 = QtWidgets.QCheckBox(Dialog)
        self.K46.setGeometry(QtCore.QRect(230, 370, 70, 17))
        self.K46.setObjectName("K46")
        self.led47 = LedWidget(Dialog)
        self.led47.setGeometry(QtCore.QRect(290, 390, 21, 21))
        self.led47.setObjectName("led47")
        self.K42 = QtWidgets.QCheckBox(Dialog)
        self.K42.setGeometry(QtCore.QRect(230, 290, 70, 17))
        self.K42.setObjectName("K42")
        self.led44 = LedWidget(Dialog)
        self.led44.setGeometry(QtCore.QRect(290, 330, 21, 21))
        self.led44.setObjectName("led44")
        self.led43 = LedWidget(Dialog)
        self.led43.setGeometry(QtCore.QRect(290, 310, 21, 21))
        self.led43.setObjectName("led43")
        self.chkSelectbank3 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank3.setGeometry(QtCore.QRect(230, 440, 91, 17))
        self.chkSelectbank3.setObjectName("chkSelectbank3")
        self.led45 = LedWidget(Dialog)
        self.led45.setGeometry(QtCore.QRect(290, 350, 21, 21))
        self.led45.setObjectName("led45")
        self.K41 = QtWidgets.QCheckBox(Dialog)
        self.K41.setGeometry(QtCore.QRect(230, 270, 70, 17))
        self.K41.setObjectName("K41")
        self.led46 = LedWidget(Dialog)
        self.led46.setGeometry(QtCore.QRect(290, 370, 21, 21))
        self.led46.setObjectName("led46")
        self.led48 = LedWidget(Dialog)
        self.led48.setGeometry(QtCore.QRect(290, 410, 21, 21))
        self.led48.setObjectName("led48")
        self.K48 = QtWidgets.QCheckBox(Dialog)
        self.K48.setGeometry(QtCore.QRect(230, 410, 70, 17))
        self.K48.setObjectName("K48")
        self.K45 = QtWidgets.QCheckBox(Dialog)
        self.K45.setGeometry(QtCore.QRect(230, 350, 70, 17))
        self.K45.setObjectName("K45")
        self.led41 = LedWidget(Dialog)
        self.led41.setGeometry(QtCore.QRect(290, 270, 21, 21))
        self.led41.setObjectName("led41")
        self.led58 = LedWidget(Dialog)
        self.led58.setGeometry(QtCore.QRect(390, 290, 21, 21))
        self.led58.setObjectName("led58")
        self.K59 = QtWidgets.QCheckBox(Dialog)
        self.K59.setGeometry(QtCore.QRect(330, 310, 70, 17))
        self.K59.setObjectName("K59")
        self.K63 = QtWidgets.QCheckBox(Dialog)
        self.K63.setGeometry(QtCore.QRect(330, 390, 70, 17))
        self.K63.setObjectName("K63")
        self.K60 = QtWidgets.QCheckBox(Dialog)
        self.K60.setGeometry(QtCore.QRect(330, 330, 70, 17))
        self.K60.setObjectName("K60")
        self.K62 = QtWidgets.QCheckBox(Dialog)
        self.K62.setGeometry(QtCore.QRect(330, 370, 70, 17))
        self.K62.setObjectName("K62")
        self.led63 = LedWidget(Dialog)
        self.led63.setGeometry(QtCore.QRect(390, 390, 21, 21))
        self.led63.setObjectName("led63")
        self.K58 = QtWidgets.QCheckBox(Dialog)
        self.K58.setGeometry(QtCore.QRect(330, 290, 70, 17))
        self.K58.setObjectName("K58")
        self.led60 = LedWidget(Dialog)
        self.led60.setGeometry(QtCore.QRect(390, 330, 21, 21))
        self.led60.setObjectName("led60")
        self.led59 = LedWidget(Dialog)
        self.led59.setGeometry(QtCore.QRect(390, 310, 21, 21))
        self.led59.setObjectName("led59")
        self.chkSelectbank4 = QtWidgets.QCheckBox(Dialog)
        self.chkSelectbank4.setGeometry(QtCore.QRect(330, 440, 91, 17))
        self.chkSelectbank4.setObjectName("chkSelectbank4")
        self.led61 = LedWidget(Dialog)
        self.led61.setGeometry(QtCore.QRect(390, 350, 21, 21))
        self.led61.setObjectName("led61")
        self.K57 = QtWidgets.QCheckBox(Dialog)
        self.K57.setGeometry(QtCore.QRect(330, 270, 70, 17))
        self.K57.setObjectName("K57")
        self.led62 = LedWidget(Dialog)
        self.led62.setGeometry(QtCore.QRect(390, 370, 21, 21))
        self.led62.setObjectName("led62")
        self.led64 = LedWidget(Dialog)
        self.led64.setGeometry(QtCore.QRect(390, 410, 21, 21))
        self.led64.setObjectName("led64")
        self.K64 = QtWidgets.QCheckBox(Dialog)
        self.K64.setGeometry(QtCore.QRect(330, 410, 70, 17))
        self.K64.setObjectName("K64")
        self.K61 = QtWidgets.QCheckBox(Dialog)
        self.K61.setGeometry(QtCore.QRect(330, 350, 70, 17))
        self.K61.setObjectName("K61")
        self.led57 = LedWidget(Dialog)
        self.led57.setGeometry(QtCore.QRect(390, 270, 21, 21))
        self.led57.setObjectName("led57")
        self.lblheader = QtWidgets.QLabel(Dialog)
        self.lblheader.setGeometry(QtCore.QRect(30, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.lblheader.setFont(font)
        self.lblheader.setObjectName("lblheader")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 480, 391, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lblboardid_2 = QtWidgets.QLabel(Dialog)
        self.lblboardid_2.setGeometry(QtCore.QRect(30, 460, 47, 13))
        self.lblboardid_2.setObjectName("lblboardid_2")
        self.K51.raise_()
        self.K1_2.raise_()
        self.K1.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.GPIO1_2.raise_()
        self.checkBox_4.raise_()
        self.GPIO1_3.raise_()
        self.GPIO1_4.raise_()
        self.checkBox_5.raise_()
        self.lblboardid.raise_()
        self.plainTextEdit_4.raise_()
        self.led1.raise_()
        self.led2.raise_()
        self.led3.raise_()
        self.led4.raise_()
        self.led6.raise_()
        self.led5.raise_()
        self.led8.raise_()
        self.led7.raise_()
        self.lblBank3.raise_()
        self.lblBank4.raise_()
        self.lblBank2.raise_()
        self.lblBank1.raise_()
        self.K19.raise_()
        self.led19.raise_()
        self.led21.raise_()
        self.led17.raise_()
        self.K18.raise_()
        self.K21.raise_()
        self.K22.raise_()
        self.led22.raise_()
        self.led24.raise_()
        self.K20.raise_()
        self.K24.raise_()
        self.K17.raise_()
        self.led20.raise_()
        self.K23.raise_()
        self.led18.raise_()
        self.led23.raise_()
        self.led33.raise_()
        self.led34.raise_()
        self.K38.raise_()
        self.led38.raise_()
        self.led36.raise_()
        self.K35.raise_()
        self.K40.raise_()
        self.led37.raise_()
        self.led39.raise_()
        self.K37.raise_()
        self.led40.raise_()
        self.led35.raise_()
        self.K39.raise_()
        self.K34.raise_()
        self.K36.raise_()
        self.K33.raise_()
        self.K54.raise_()
        self.led51_2.raise_()
        self.led55.raise_()
        self.led51.raise_()
        self.K53.raise_()
        self.K56.raise_()
        self.led49.raise_()
        self.led54.raise_()
        self.K55.raise_()
        self.led53.raise_()
        self.K52.raise_()
        self.led50.raise_()
        self.led56.raise_()
        self.K50.raise_()
        self.K49.raise_()
        self.chkSelectbank1.raise_()
        self.led11.raise_()
        self.led10.raise_()
        self.GPIO1_17.raise_()
        self.led14.raise_()
        self.GPIO1_18.raise_()
        self.led12.raise_()
        self.led16.raise_()
        self.led13.raise_()
        self.led15.raise_()
        self.checkBox_22.raise_()
        self.checkBox_23.raise_()
        self.checkBox_24.raise_()
        self.checkBox_25.raise_()
        self.GPIO1_19.raise_()
        self.led9.raise_()
        self.led26.raise_()
        self.K27.raise_()
        self.K31.raise_()
        self.K28.raise_()
        self.K30.raise_()
        self.led31.raise_()
        self.K26.raise_()
        self.led28.raise_()
        self.led27.raise_()
        self.chkSelectbank2.raise_()
        self.led29.raise_()
        self.K25.raise_()
        self.led30.raise_()
        self.led32.raise_()
        self.K32.raise_()
        self.K29.raise_()
        self.led25.raise_()
        self.led42.raise_()
        self.K43.raise_()
        self.K47.raise_()
        self.K44.raise_()
        self.K46.raise_()
        self.led47.raise_()
        self.K42.raise_()
        self.led44.raise_()
        self.led43.raise_()
        self.chkSelectbank3.raise_()
        self.led45.raise_()
        self.K41.raise_()
        self.led46.raise_()
        self.led48.raise_()
        self.K48.raise_()
        self.K45.raise_()
        self.led41.raise_()
        self.led58.raise_()
        self.K59.raise_()
        self.K63.raise_()
        self.K60.raise_()
        self.K62.raise_()
        self.led63.raise_()
        self.K58.raise_()
        self.led60.raise_()
        self.led59.raise_()
        self.chkSelectbank4.raise_()
        self.led61.raise_()
        self.K57.raise_()
        self.led62.raise_()
        self.led64.raise_()
        self.K64.raise_()
        self.K61.raise_()
        self.led57.raise_()
        self.lblheader.raise_()
        self.plainTextEdit.raise_()
        self.lblboardid_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.K1.setText(_translate("Dialog", "K1"))
        self.checkBox_2.setText(_translate("Dialog", "K2"))
        self.checkBox_3.setText(_translate("Dialog", "K4"))
        self.GPIO1_2.setText(_translate("Dialog", "K3"))
        self.checkBox_4.setText(_translate("Dialog", "K6"))
        self.GPIO1_3.setText(_translate("Dialog", "K7"))
        self.GPIO1_4.setText(_translate("Dialog", "K5"))
        self.checkBox_5.setText(_translate("Dialog", "K8"))
        self.lblboardid.setText(_translate("Dialog", "Board ID"))
        self.lblBank3.setText(_translate("Dialog", "BANK 3"))
        self.lblBank4.setText(_translate("Dialog", "BANK 4"))
        self.lblBank2.setText(_translate("Dialog", "BANK 2"))
        self.lblBank1.setText(_translate("Dialog", "BANK 1"))
        self.K19.setText(_translate("Dialog", "K19"))
        self.K18.setText(_translate("Dialog", "K18"))
        self.K21.setText(_translate("Dialog", "K21"))
        self.K22.setText(_translate("Dialog", "K22"))
        self.K20.setText(_translate("Dialog", "K20"))
        self.K24.setText(_translate("Dialog", "K24"))
        self.K17.setText(_translate("Dialog", "K17"))
        self.K23.setText(_translate("Dialog", "K23"))
        self.K38.setText(_translate("Dialog", "K38"))
        self.K35.setText(_translate("Dialog", "K35"))
        self.K40.setText(_translate("Dialog", "K40"))
        self.K37.setText(_translate("Dialog", "K37"))
        self.K39.setText(_translate("Dialog", "K39"))
        self.K34.setText(_translate("Dialog", "K34"))
        self.K36.setText(_translate("Dialog", "K36"))
        self.K33.setText(_translate("Dialog", "K33"))
        self.K54.setText(_translate("Dialog", "K54"))
        self.K53.setText(_translate("Dialog", "K53"))
        self.K56.setText(_translate("Dialog", "K56"))
        self.K55.setText(_translate("Dialog", "K55"))
        self.K52.setText(_translate("Dialog", "K52"))
        self.K51.setText(_translate("Dialog", "K51"))
        self.K50.setText(_translate("Dialog", "K50"))
        self.K49.setText(_translate("Dialog", "K49"))
        self.chkSelectbank1.setText(_translate("Dialog", "Select Bank 1"))
        self.K1_2.setText(_translate("Dialog", "K9"))
        self.GPIO1_17.setText(_translate("Dialog", "K11"))
        self.GPIO1_18.setText(_translate("Dialog", "K15"))
        self.checkBox_22.setText(_translate("Dialog", "K12"))
        self.checkBox_23.setText(_translate("Dialog", "K14"))
        self.checkBox_24.setText(_translate("Dialog", "K16"))
        self.checkBox_25.setText(_translate("Dialog", "K10"))
        self.GPIO1_19.setText(_translate("Dialog", "K13"))
        self.K27.setText(_translate("Dialog", "K27"))
        self.K31.setText(_translate("Dialog", "K31"))
        self.K28.setText(_translate("Dialog", "K28"))
        self.K30.setText(_translate("Dialog", "K30"))
        self.K26.setText(_translate("Dialog", "K26"))
        self.chkSelectbank2.setText(_translate("Dialog", "Select Bank 2"))
        self.K25.setText(_translate("Dialog", "K25"))
        self.K32.setText(_translate("Dialog", "K32"))
        self.K29.setText(_translate("Dialog", "K29"))
        self.K43.setText(_translate("Dialog", "K43"))
        self.K47.setText(_translate("Dialog", "K47"))
        self.K44.setText(_translate("Dialog", "K44"))
        self.K46.setText(_translate("Dialog", "K46"))
        self.K42.setText(_translate("Dialog", "K42"))
        self.chkSelectbank3.setText(_translate("Dialog", "Select Bank 3"))
        self.K41.setText(_translate("Dialog", "K41"))
        self.K48.setText(_translate("Dialog", "K48"))
        self.K45.setText(_translate("Dialog", "K45"))
        self.K59.setText(_translate("Dialog", "K59"))
        self.K63.setText(_translate("Dialog", "K63"))
        self.K60.setText(_translate("Dialog", "K60"))
        self.K62.setText(_translate("Dialog", "K62"))
        self.K58.setText(_translate("Dialog", "K58"))
        self.chkSelectbank4.setText(_translate("Dialog", "Select Bank 4"))
        self.K57.setText(_translate("Dialog", "K57"))
        self.K64.setText(_translate("Dialog", "K64"))
        self.K61.setText(_translate("Dialog", "K61"))
        self.lblheader.setText(_translate("Dialog", "THRC BOARD CHECK"))
        self.lblboardid_2.setText(_translate("Dialog", "Console"))

from ledwidget import LedWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

